# Generated by Django 6.0.5 on 2026-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('dos', 'DOS'), ('principal', 'Principal'), ('bursar', 'Bursar'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='student', max_length=20),
        ),
    ]
