# Generated by Django 6.0.5 on 2026-06-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('students', '0003_studentloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.stream'),
        ),
    ]
