# Generated by Django 6.0.5 on 2026-05-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_app_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='classes.class'),
        ),
    ]
