# Generated by Django 6.0.5 on 2026-06-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0005_rename_class_assigned_teachersubjectassignment_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastered_classes', to='teachers.teacher'),
        ),
    ]
