# Generated by Django 6.0.5 on 2026-05-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_initial'),
        ('schools', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.term'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('exam', 'term', 'student', 'subject')},
        ),
    ]
