# Generated by Django 6.0.5 on 2026-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('OPENING', 'Opening Exam'), ('MIDTERM', 'Midterm Exam'), ('END_TERM', 'End Term Exam'), ('CAT', 'CAT'), ('FINAL', 'Final')], max_length=20),
        ),
    ]
