# Generated by Django 6.0.5 on 2026-06-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_classteacher_classteacherassignment_teachersubject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTeacher',
        ),
    ]
