# Generated by Django 6.0.5 on 2026-06-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0004_delete_classteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersubjectassignment',
            old_name='class_assigned',
            new_name='class_obj',
        ),
        migrations.RemoveField(
            model_name='classteacherassignment',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='classteacherassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teachersubjectassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teachersubjectassignment',
            name='school',
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.stream'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.stream'),
        ),
    ]
