# Generated by Django 6.0.5 on 2026-06-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_class_master'),
        ('schools', '0009_school_deactivated_at_school_deactivation_reason_and_more'),
        ('teachers', '0005_rename_class_assigned_teachersubjectassignment_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classteacherassignment',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.stream'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classteacherassignment',
            unique_together={('class_obj', 'stream')},
        ),
    ]
