# Generated by Django 6.0.5 on 2026-06-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_class_master'),
        ('subjects', '0004_alter_subject_code'),
        ('teachers', '0006_teachersubjectassignment_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_subjects',
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('class_obj', 'stream', 'subject')},
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
