# Generated by Django 6.0.5 on 2026-05-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='instructions',
        ),
    ]
