# Generated by Django 6.0.5 on 2026-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_description_assignment_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
