# Generated by Django 6.0.5 on 2026-05-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSubject',
        ),
    ]
