# Generated by Django 6.0.5 on 2026-05-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_delete_teachersubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('school', 'name', 'start_date')},
        ),
    ]
