# Generated by Django 6.0.5 on 2026-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_motto_schoolnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
