# Generated by Django 6.0.5 on 2026-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingpolicy',
            name='grade_letter',
            field=models.CharField(max_length=100),
        ),
    ]
