# Generated by Django 6.0.5 on 2026-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_alter_gradingpolicy_grade_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingpolicy',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
