# Generated by Django 6.0.5 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_school_is_verified_school_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='opening_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='closing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
