# Generated by Django 6.0.5 on 2026-07-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_contactmessage_studentmark_exam'),
    ]

    operations = [
    ]
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0017_contactmessage_studentmark_exam"),
        ("exams", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmark",
            name="exam",
            field=models.ForeignKey(
                to="exams.exam",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]