# Generated by Django 6.0.5 on 2026-07-10 16:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_add_exam_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='closing_datetime',
        ),
        migrations.RemoveField(
            model_name='term',
            name='opening_datetime',
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
