# Generated by Django 6.0.5 on 2026-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_add_error_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
