# Generated by Django 6.0.5 on 2026-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_security_and_error_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='browser_used',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
