# Generated by Django 6.0.5 on 2026-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_contactmessage_browser_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
