# Generated by Django 6.0.5 on 2026-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_contactmessage_replied_at_contactmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
