# Generated by Django 6.0.5 on 2026-07-26 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_supportagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +2547XXXXXXXX or +2541XXXXXXXX.', regex='^\\+254[17]\\d{8}$')]),
        ),
    ]
