# Generated by Django 6.0.5 on 2026-05-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('schools', '0006_delete_classsubject'),
        ('subjects', '0001_initial'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'unique_together': {('class_name', 'subject')},
            },
        ),
    ]
