# Generated by Django 6.0.5 on 2026-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
