# Generated by Django 6.0.5 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.IntegerField(),
        ),
    ]
